/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.creocode.catalog;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int titleBackgroud=0x7f040000;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int ItemScrollView=0x7f060003;
        public static final int ItemTextViewContent=0x7f060001;
        public static final int OptionsBGLabel=0x7f060006;
        public static final int OptionsFontLabel=0x7f06000a;
        public static final int OptionsLayout=0x7f060004;
        public static final int OptionsRadioButtonBGDark=0x7f060008;
        public static final int OptionsRadioButtonBGLight=0x7f060007;
        public static final int OptionsRadioButtonFontLarge=0x7f06000d;
        public static final int OptionsRadioButtonFontMedium=0x7f06000c;
        public static final int OptionsRadioButtonFontSmall=0x7f06000b;
        public static final int OptionsRadioGroupBackground=0x7f060005;
        public static final int OptionsRadioGroupFont=0x7f060009;
        public static final int buttonNext=0x7f060002;
        public static final int linearLayout=0x7f060000;
    }
    public static final class layout {
        public static final int item_view=0x7f030000;
        public static final int item_view_scroll=0x7f030001;
        public static final int options_view=0x7f030002;
    }
    public static final class string {
        public static final int app_copyrights=0x7f05000a;
        public static final int app_name=0x7f050000;
        public static final int contact=0x7f050011;
        public static final int eula_accept=0x7f05000c;
        public static final int eula_refuse=0x7f05000d;
        public static final int eula_title=0x7f05000b;
        public static final int next=0x7f050010;
        public static final int options_bg=0x7f050004;
        public static final int options_bg_dark=0x7f050003;
        public static final int options_bg_light=0x7f050002;
        public static final int options_font=0x7f050008;
        public static final int options_font_large=0x7f050007;
        public static final int options_font_medium=0x7f050006;
        public static final int options_font_small=0x7f050005;
        public static final int options_label=0x7f050001;
        public static final int options_save=0x7f050009;
        public static final int pop_up=0x7f05000f;
        public static final int visit_creocode=0x7f05000e;
    }
}
