/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.creocode.catalog.validation;

import com.creocode.catalog.DetailsType;

/**
 * A sample validator interface for {@link com.creocode.catalog.ItemType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemTypeValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateContent(String value);
	boolean validateIntro(String value);
	boolean validateDetails(DetailsType value);
}
